
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check if app.js is running
        id: pm2-check
        run: |
          if pm2 show app; then
            echo "App is already running with PM2."
            echo "::set-output name=app_running::true"
          else
            echo "App is not running with PM2."
            echo "::set-output name=app_running::false"
          fi
      - name: Install NPM packages
        run: npm i
      - name: Start or Stop app.js with PM2
        run: |
          if [[ "${{ steps.pm2-check.outputs.app_running }}" == "true" ]]; then
            echo "Stopping app.js with PM2"
            pm2 stop app
          else
            echo "Starting app.js with PM2"
            pm2 start -f app.js
            pm2 save
          fi
      - name: Restart Nginx (if needed)
        run: |
          if [[ "${{ steps.pm2-check.outputs.app_running }}" == "true" ]]; then
            echo "App is already running, no need to restart Nginx."
          else
            echo "App was started or restarted, restarting Nginx..."
            echo "mtechub123" | sudo -S sudo service nginx restart
          fi



